### ISSUE TITLE
Detail Data Preparation

### ISSUE THREAD

**Issue by luongphambao** [christopherohit/nerf_data_preprocessing#1]
**Can you provide me with the method to prepare the data as well as the step-by-step process to do it?**

**Comment by christopherohit** [comment]
first of all, you need to clone the repo sync-talk here: https://github.com/ZiqiaoPeng/SyncTalk
after that, you clone this project and place all folders and files into synctalk repo,
Finally, you make it like introduce in this repo or synctalk

Update: Synctalk nearly updated their source, they public their data processing but it looks like different our method, you can try both

**Comment by christopherohit** [comment]
first of all, you need to clone the repo sync-talk here: https://github.com/ZiqiaoPeng/SyncTalk
after that, you clone this project and place all folders and files into synctalk repo,
Finally, you make it like introduce in this repo or synctalk

Update: Synctalk nearly updated their source, they public their data processing but it looks like different our method, you can try both

**Comment by luongphambao** [comment]
Thank you. I will close this issue
